### PR TITLE
Scheduling

### LINKED ISSUE #20: Scheduling

### PR DESCRIPTION
**Pull request by LucaScorpion**
Fixes #20 

- Implement script scheduling based on cron expressions.
- Script attributes are now editable, the new script page is used for both creating and editing scripts.

### CODE REVIEW

**Comment by ChappIO** [comment]
I was looking at your solution and wondering if you considered a new entity called 'Schedule'.

If we had this, we would be able to model it the same way we do script triggers (#13).

**Comment by LucaScorpion** [comment]
@ChappIO Good question, I have thought about it but I wanted to start out with a simpler approach to see how it all had to work. I feel separating the schedule to an entity makes sense if we want to configure schedules on a project level (instead of a script level as they are now) or if we want to change the scheduling method (instead of using cron expressions), both of which I feel we probably want to do. However, it would be good to discuss this some more so I've added an item to the next meeting agenda.

**Comment by LucaScorpion** [comment]
From the meeting notes:

We’ve decided to stick with cron expressions, and to add some utilities to the frontend to make them easier to create. One possible utility would be to show the meaning of the expression in natural language. Another option would be to show the date/time of the next run while editing the expression. If it’s viable to implement both that would be nice, otherwise one would suffice.

A schedule entity should be added which can be used as the trigger for a job. Schedules will be moved up to the project level so that you can define multiple schedules for one script with different arguments.

**Comment by ChappIO** [comment]
I have been taking a look at scheduling as a 'new' user. Here are my comments:

- The json input has to be typed into a text field now. Could we consider a small ace editor with json validaton?
- The cron pattern help refers to the documentation, should I go there? Have you thought about the delivery to the user of this documentation? Maybe we should add some examples to the cron pattern as well. (I like the graphic btw, very nice)
- I don't seem to have the natural language or the 'next' run assistant while typing the cron pattern. I think that is the most important place to see it.
- I like the icon as a schedule trigger so much, should we also do this for jobs? So instead of `#4` just show the script icon and on hover you can see the name?

A lot of ideas, but I guess that's frontend/ux. I really like the work you did.

**Comment by LucaScorpion** [comment]
Thanks for the feedback :) I'll address your points one by one:

- Good idea, I'll have a look and see if I can make that work.
- Yeah, I've added a section to the documentation which explains cron patterns and the special characters along with a bunch of examples, but I wasn't sure how we wanted to publish that. Once we have that set up the help popup could actually link to it. Adding some examples there too is a good idea, I'll do that.
- Good point, after a bit I got so used to the patterns that that didn't feel necessary but I agree that especially for newer users it makes it a lot easier to work with.
- I think that would be better yes, the id's don't tell you much anyway and an icon is probably clearer.

Most of these shouldn't be too difficult so I'll probably fix them somewhere today. The only thing I'm unsure about is how we're going to publish the documentation (purely practical, as in how do we take the generated html and package it with the app so it works when running in dev as well as in prod from a docker image).

**Comment by bobvdvalk** [comment]
I would like to see that the schedular is tested and is passing the quality gate on SonarQube. 

Nice changes on the UI :+1:

**Comment by LucaScorpion** [comment]
I'm not sure if I'll be able to make the quality gate pass, since a lot of added code is frontend for which we have no testing infrastructure set up (yet), but I'll have a look at testing the scheduler. Thanks :)

**Comment by LucaScorpion** [comment]
@ChappIO 
I've addressed your points except for the documentation, since we might want to think more about what we want to do with that so that would be better for another issue. I've also left out live updating the schedule's next run time, because I feel like that changing doesn't make much sense given that it's part of a different field in the form right now (but we could ofc discuss this if you want). I did add the live updating for the natural language description.

@bobvdvalk 
I've added a bunch of tests, so now (almost) everything is fully tested, except for the web controllers.

**Pull request merged**
